[package]
name = "bitcrypto"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
siphasher = "0.1.1"
primitives = { path = "../primitives", default-features = false }
sr-std = { git = "https://github.com/paritytech/substrate", default-features = false }
